services: 
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    volumes:
      - .:/backend
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: ${P_DB}
      POSTGRES_USER: ${P_USER}
      POSTGRES_PASSWORD: ${P_PASS}
    ports:
      - "5432:5432"
