services: 
  api:
    build:
      dockerfile: docker/api/Dockerfile
      context: .
    volumes:
      - .:/backend
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
      - migrations
    ports:
      - "8000:8000"

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_DB: ${P_DB}
      POSTGRES_USER: ${P_USER}
      POSTGRES_PASSWORD: ${P_PASS}
    ports:
      - "5432:5432"

  migrations:
    build:
      dockerfile: docker/migrations/Dockerfile
      context: .
    container_name: yoyo-migrations
    depends_on:
      - postgres
    restart: on-failure:10
    volumes:
      - ./migrations:/migrations
    command: yoyo apply --database ${DATABASE_URL} /migrations


volumes:
  postgres_data: